name: D8TAVu_web
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask
  - pandas
  - matplotlib
  - yfinance
  - numpy
  - requests
  - beautifulsoup4
  - python-dateutil
  - pytz
  - brotli
  - wfastcgi
  - brotlicffi=1.1.0.0
  - brotlipy=0.7.0
  - werkzeug=3.1.3
  - mplfinance=0.12.9b7
