name: D8TAVu_web
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.3.3
  - werkzeug=2.3.7
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - yfinance>=0.2.28
  - numpy>=1.24.0
  - requests>=2.31.0
  - beautifulsoup4>=4.12.0
  - python-dateutil>=2.8.2
  - pytz>=2023.3
  - brotli>=1.0.9
  - wfastcgi>=3.0.0
  - brotlicffi=1.1.0.0
  - brotlipy=0.7.0
  - mplfinance=0.12.9b7
  - pip>=23.0.0
  - setuptools>=68.0.0
  - wheel>=0.41.0
